# Copyright 2024 CraigBuilds
# Licensed under the Apache License, Version 2.0
"""Template rendering for systemd service units and wrapper scripts."""

from pathlib import Path
from typing import Optional

from colcon_systemd.config import ServiceConfig

# We use direct execution of installed entry points / executables with a
# wrapper script that sources the colcon workspace setup.bash.
#
# Rationale for direct execution over `ros2 run`:
# - No runtime dependency on the `ros2` CLI tools
# - Simpler failure semantics (no intermediary process)
# - The installed entry point is a real executable; systemd can manage it
#   directly, send signals, and track the PID
# - The wrapper script handles environment sourcing, which is the only thing
#   `ros2 run` would additionally provide
# - Users who want `ros2 run` can trivially write their own wrapper

_SERVICE_TEMPLATE = """\
[Unit]
Description={description}
After={after}

[Service]
Type=simple
ExecStart={exec_start}
{environment_lines}\
Restart={restart}
{working_directory_line}\

[Install]
WantedBy=default.target
"""

_WRAPPER_TEMPLATE = """\
#!/usr/bin/env bash
# Auto-generated by colcon-systemd — do not edit
# Note: -u (nounset) is intentionally omitted because colcon's setup.bash
# references variables like COLCON_TRACE that may be unset.
set -eo pipefail
source "{setup_bash}"
exec "{executable}" "$@"
"""


def _resolve_setup_bash(install_base: Path, merge_install: bool) -> str:
    """
    Find the workspace-level setup.bash.

    In isolated mode (default), install_base is ``<ws>/install/<pkg>``
    and setup.bash is at ``<ws>/install/setup.bash`` (one level up).
    In merged mode, install_base is ``<ws>/install`` and setup.bash
    is right there.
    """
    if merge_install:
        return str(install_base / "setup.bash")
    return str(install_base.parent / "setup.bash")


def _resolve_executable_path(
    install_base: Path,
    package_name: str,
    service: ServiceConfig,
    package_type: str,
) -> str:
    """
    Determine the absolute path to the executable for a service.

    ``install_base`` is the per-package install prefix that colcon passes
    to each build task.  In isolated mode this is already
    ``<ws>/install/<pkg>``, so we do **not** append the package name again.

    For ament_python / ros.ament_python packages, entry_point refers to a
    console_scripts entry point installed by setuptools.  colcon installs
    these into ``<install_base>/lib/<pkg>/<entry_point>``.

    For other package types, the executable path follows the same convention
    when using 'executable', or falls back to 'entry_point' with the same
    layout.
    """
    ep = service.entry_point or service.executable
    if ep is None:
        raise ValueError(
            f"Service '{service.name}' has neither entry_point nor executable; "
            "this is a validation bug — parse_config should have caught it."
        )
    return str(install_base / "lib" / package_name / ep)


def render_wrapper_script(
    install_base: Path,
    package_name: str,
    service: ServiceConfig,
    package_type: str,
    merge_install: bool = False,
) -> str:
    """
    Render a bash wrapper script that sources the workspace and execs the node.

    :param install_base: Per-package install prefix (colcon ``args.install_base``).
    :param package_name: Name of the package.
    :param service: Parsed service configuration.
    :param package_type: The colcon package type string.
    :param merge_install: True when ``--merge-install`` is active.
    :returns: The rendered script content as a string.
    """
    setup_bash = _resolve_setup_bash(install_base, merge_install)
    executable = _resolve_executable_path(
        install_base, package_name, service, package_type
    )
    return _WRAPPER_TEMPLATE.format(
        setup_bash=setup_bash,
        executable=executable,
    )


def render_service_unit(
    install_base: Path,
    package_name: str,
    service: ServiceConfig,
    package_type: str,
    wrapper_script_path: Path,
) -> str:
    """
    Render a systemd service unit file.

    :param install_base: Per-package install prefix (colcon ``args.install_base``).
    :param package_name: Name of the package.
    :param service: Parsed service configuration.
    :param package_type: The colcon package type string.
    :param wrapper_script_path: Absolute path to the generated wrapper script.
    :returns: The rendered unit file content as a string.
    """
    description = service.description or f"{package_name} {service.name}"
    after = " ".join(service.after)
    exec_start = str(wrapper_script_path)
    if service.args:
        exec_start += " " + " ".join(service.args)

    env_lines = ""
    for key, value in service.environment.items():
        env_lines += f'Environment="{key}={value}"\n'

    wd_line = ""
    if service.working_directory:
        wd_line = f"WorkingDirectory={service.working_directory}\n"

    return _SERVICE_TEMPLATE.format(
        description=description,
        after=after,
        exec_start=exec_start,
        environment_lines=env_lines,
        restart=service.restart,
        working_directory_line=wd_line,
    )


def write_service_files(
    install_base: Path,
    package_name: str,
    service: ServiceConfig,
    package_type: str,
    merge_install: bool = False,
) -> Optional[Path]:
    """
    Generate the wrapper script and systemd unit for a single service.

    ``install_base`` is the per-package install prefix from colcon.  In
    isolated mode (the default) this is ``<ws>/install/<pkg>``.  Files
    are written under this prefix:

      ``<install_base>/share/colcon-systemd/<service>.sh``
      ``<install_base>/share/colcon-systemd/<service>.service``

    :param merge_install: True when ``--merge-install`` is active.
    :returns: Path to the generated .service file, or None on failure.
    """
    output_dir = install_base / "share" / "colcon-systemd"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write wrapper script
    wrapper_path = output_dir / f"{service.name}.sh"
    wrapper_content = render_wrapper_script(
        install_base, package_name, service, package_type,
        merge_install=merge_install,
    )
    wrapper_path.write_text(wrapper_content)
    wrapper_path.chmod(0o755)

    # Write service unit
    service_path = output_dir / f"{service.name}.service"
    unit_content = render_service_unit(
        install_base, package_name, service, package_type, wrapper_path
    )
    service_path.write_text(unit_content)

    return service_path
